rem This batch file sets up a test for TIMID-II. Just name the file you
rem want to infect as 001.COM, and run this file. You will create 29 copies
rem of it in the current directory and 15 in a subdirectory called t.
copy 001.com 002.com
copy 001.com 003.com
copy 001.com 004.com
copy 001.com 005.com
copy 001.com 006.com
copy 001.com 007.com
copy 001.com 008.com
copy 001.com 009.com
copy 001.com 010.com
copy 001.com 011.com
copy 001.com 012.com
copy 001.com 013.com
copy 001.com 014.com
copy 001.com 015.com
md t
copy 001.com t\001.com
cd t
copy 001.com 002.com
copy 001.com 003.com
copy 001.com 004.com
copy 001.com 005.com
copy 001.com 006.com
copy 001.com 007.com
copy 001.com 008.com
copy 001.com 009.com
copy 001.com 010.com
copy 001.com 011.com
copy 001.com 012.com
copy 001.com 013.com
copy 001.com 014.com
copy 001.com 015.com
cd ..
copy 001.com 016.com
copy 001.com 017.com
copy 001.com 018.com
copy 001.com 019.com
copy 001.com 020.com
copy 001.com 021.com
copy 001.com 022.com
copy 001.com 023.com
copy 001.com 024.com
copy 001.com 025.com
copy 001.com 026.com
copy 001.com 027.com
copy 001.com 028.com
copy 001.com 029.com
